//
// Created by wei on 16-12-4.
//
#define   LOG_TAG    "NATIVE FREYA JNI"
//#define   LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

#ifndef AESJNIENCRYPT_SIGNACTURECHECK_H
#define AESJNIENCRYPT_SIGNACTURECHECK_H

#ifdef  __cplusplus

extern "C" {

#endif

/* C头文件的其它声明 */

//合法的APP包名
static const char *app_packageName = "com.mango.vpn";
//this value is generated by com.androidyuan.aesjni.SignatureTool.java.
//-625644214 is hash of keystore file.
static const int app_signature_hash_code = -1909109625;

/**
 * 校验APP 包名和签名是否合法
 *
 * 返回值为1 表示合法
 */
jint check_signature(JNIEnv *env, jobject context);

#ifdef  __cplusplus

}

#endif  /* end of __cplusplus */


#endif //AESJNIENCRYPT_SIGNACTURECHECK_H
